
package(default_visibility = ["//visibility:public"])

java_library(
    name = "AppLib",
    srcs = glob(["*.java"]),
)

java_binary(
    name = "AppBin",
	main_class = "src.frog.Frog",
	srcs = glob(["*.java"]),
)
