/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FLOG_GUI;

import FLOG_LOGIC.FLOG_LOGIC;
import FLOG_LOGIC.Multiplayer;
import java.awt.Dimension;

/**
 *
 * @author Dushan Galappaththi
 */
public class ChatFrame extends javax.swing.JFrame {

    Multiplayer multiplayer=new Multiplayer();
    /**
     * Creates new form ChatFrame
     */
    GameScreen gameScreen;
    public ChatFrame(GameScreen gameScreen) 
    {
        initComponents();
        this.gameScreen = gameScreen;
        setWindow();
    }
    
    private void setWindow()
    {
        this.setSize(new Dimension(272, 619));
        this.setResizable(false);
        this.setLocation(gameScreen.getLocationOnScreen().x + gameScreen.getWidth() + 20
                , gameScreen.getLocationOnScreen().y);
        this.validate();
        this.setVisible(true);
    }
    
    public synchronized void updateMessages(String username, String msg)
    {
        String newMsg = username +" :: "+msg;
        String oldMsgs = jTextPane1.getText();
        jTextPane1.setText(oldMsgs +="\n" +newMsg);
    }
    
    public void sendClick()
    {
        
        String msg = DataForUI.currentUsername+" :: "+txtMessage.getText();
        //Broadcast the message here
        if(!msg.equals(""))
        {
            msg="110 "+msg.trim().replaceAll(" ","_");
            gameScreen.multiplayer.broadcast(DataForUI.currentChannel, gameScreen.otherPlayerNames, msg);
            System.out.println("message :" +msg +" "+ gameScreen.otherPlayerNames.size());
            updateMessages(DataForUI.currentUsername,msg);
        }
        
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContainer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        btnSend = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();
        pnlTopBorder = new javax.swing.JPanel();
        btnExit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(jTextPane1);

        pnlContainer.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 46, 252, 480));

        btnSend.setText("send");
        btnSend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSendMouseClicked(evt);
            }
        });
        pnlContainer.add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 580, -1, -1));

        txtMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMessageActionPerformed(evt);
            }
        });
        pnlContainer.add(txtMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 210, 30));

        pnlTopBorder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExit.setText("exit");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        pnlTopBorder.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 30, 20));

        pnlContainer.add(pnlTopBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 40));

        getContentPane().add(pnlContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 272, 619));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMessageActionPerformed

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnSendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSendMouseClicked
        // TODO add your handling code here:
        sendClick();
    }//GEN-LAST:event_btnSendMouseClicked

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnSend;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JPanel pnlContainer;
    private javax.swing.JPanel pnlTopBorder;
    private javax.swing.JTextField txtMessage;
    // End of variables declaration//GEN-END:variables
}
