/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FLOG_GUI;

import java.awt.Component;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Dushan Galappaththi
 */
public class PanelSettings extends javax.swing.JPanel {

    /**
     * Creates new form PanelSettings
     */
    private Image bg;
    public PanelSettings() {
        initComponents();
          bg = new ImageIcon(getClass().getResource("/images/bg_settings.png")).getImage();
    }
    
    public void setIcon_Back(ImageIcon icon)
    {
        this.btnBack.setIcon(icon);
    
    }
    public void setIcon_Sound(ImageIcon icon)
    {
        this.btnSound.setIcon(icon);
    
    }
    public void setIcon_VolReduce(ImageIcon icon)
    {
        this.btnVolReduce.setIcon(icon);
    
    }
    public void setIcon_VolIncrease(ImageIcon icon)
    {
        this.btnVolIncrease.setIcon(icon);
    
    }
    
    public Component getCompTop(int x)
    {
        Component[] cmpList = this.getComponents();
        
        for(int i =0;i<cmpList.length;i++)
        {
              System.out.println(i + " "+cmpList[i].getY()+" "+ cmpList[i].getName() );
        }
        return this.pnlTopBorder.getComponent(x);
    }
    
      public Component getCompCon(int x)
    {
        Component[] cmpList = this.getComponents();
        
        for(int i =0;i<cmpList.length;i++)
        {
              System.out.println(i + " "+cmpList[i].getY()+" "+ cmpList[i].getName() );
        }
        return this.getComponent(x);
    }
    
    public void setSoundLevel(int x)
    {
        this.lblLevel.setText(""+x);
    }
    public void setPlayerName(String name)
    {
        this.txtName.setText(name);
    }
    public String getplayerName()
    {
        return this.txtName.getText();
    }
    
    
  @Override
    protected void paintComponent(Graphics g) 
    {
         g.drawImage(bg, 0, 0, getWidth(), getHeight(), this);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTopBorder = new javax.swing.JPanel();
        btnBack = new javax.swing.JLabel();
        btnSound = new javax.swing.JLabel();
        btnVolReduce = new javax.swing.JLabel();
        btnVolIncrease = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(900, 619));
        setMinimumSize(new java.awt.Dimension(900, 619));
        setPreferredSize(new java.awt.Dimension(900, 619));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTopBorder.setName("top"); // NOI18N
        pnlTopBorder.setOpaque(false);
        add(pnlTopBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 30));

        btnBack.setText("back");
        btnBack.setName("back"); // NOI18N
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, -1, -1));

        btnSound.setText("on/off");
        btnSound.setName("onOff"); // NOI18N
        add(btnSound, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, -1, -1));

        btnVolReduce.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnVolReduce.setText("-");
        btnVolReduce.setName("minus"); // NOI18N
        add(btnVolReduce, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, -1, -1));

        btnVolIncrease.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnVolIncrease.setText("+");
        btnVolIncrease.setName("plus"); // NOI18N
        add(btnVolIncrease, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, -1, -1));

        lblLevel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblLevel.setText("100");
        add(lblLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, -1, -1));

        txtName.setText("jTextField1");
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));

        jLabel1.setBackground(new java.awt.Color(2, 166, 229));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html><center>jLabel1<br> hi<center></html>");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 100, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnSound;
    private javax.swing.JLabel btnVolIncrease;
    private javax.swing.JLabel btnVolReduce;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JPanel pnlTopBorder;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
