/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FLOG_GUI;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.border.Border;
import javax.swing.plaf.BorderUIResource;

/**
 *
 * @author Dushan Galappaththi
 */
public class PanelPlaying extends javax.swing.JPanel {

    /**
     * Creates new form PanelPlaying
     */
    private Image bg;
    JPanel pnlOppList;
    JScrollPane jsp;
    
    public PanelPlaying() {
        initComponents();
         bg = new ImageIcon(getClass().getResource("/images/bg_playscreen.png")).getImage();
         pnlOppList = new JPanel();
         
    }
    
    public void drawPlayerName (String name)
    {
        lblPlayerName.setText(name);
    }
    public void drawPlayerScore (int score)
    {
        lblScore.setText("Score : " + String.valueOf(score));
    }
    public void drawPlayerPosition (int pos)
    {
        lblPos.setText("Position : " + String.valueOf(pos));
    }
    public void drawRoundNumber (int num)
    {
        lblRound.setText("ROUND "+String.valueOf(num));
    }
    public void drawTweleveLetters(String[] letterArr)
    {
        lblL1.setText(letterArr[0]);
        lblL2.setText(letterArr[1]);
        lblL3.setText(letterArr[2]);
        lblL4.setText(letterArr[3]);
        lblL5.setText(letterArr[4]);
        lblL6.setText(letterArr[5]);
        lblL7.setText(letterArr[6]);
        lblL8.setText(letterArr[7]);
        lblL9.setText(letterArr[8]);
        lblL10.setText(letterArr[9]);
        lblL11.setText(letterArr[10]);
        lblL12.setText(letterArr[11]);
    
    }
    
    public void drawOpponents(PlayerData[] pdArr)
    {
        pnlOppList.setLayout(new BoxLayout(pnlOppList, BoxLayout.Y_AXIS));
        pnlOppList.setOpaque(false);
        
        for(int i=0;i<pdArr.length;i++)
        {
            
            pnlOppList.add(new OpponentsUI(pdArr[i].getPosition(), pdArr[i].getName(), pdArr[i].getScore(), pdArr[i].getLetterOne(), pdArr[i].letterTwo));
        }
        
        jsp = new JScrollPane(pnlOppList);
        jsp.setOpaque(false);
        jsp.setBorder(null);
        jsp.getViewport().setOpaque(false);
        jsp.getVerticalScrollBar().setPreferredSize(new Dimension(0,0));
       // jsp
        jPanel3.add(jsp).setBounds(1, 20, 230, 510);
        
    }
    
     @Override
    protected void paintComponent(Graphics g) 
    {
         g.drawImage(bg, 0, 0, getWidth(), getHeight(), this);
    }

    public Component[] getComps()
    {
        return this.pnlPlayingArea.getComponents();
    
    }
    public Component getComp(int x)
    {
        return this.pnlPlayingArea.getComponent(x);
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitle = new javax.swing.JPanel();
        pnlContainer = new javax.swing.JPanel();
        pnlPlayingArea = new javax.swing.JPanel();
        lblPlayerName = new javax.swing.JLabel();
        lblPos = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();
        txtAnswer = new javax.swing.JTextField();
        lblL2 = new javax.swing.JLabel();
        lblL1 = new javax.swing.JLabel();
        lblL4 = new javax.swing.JLabel();
        lblL3 = new javax.swing.JLabel();
        lblL7 = new javax.swing.JLabel();
        lblL5 = new javax.swing.JLabel();
        lblL6 = new javax.swing.JLabel();
        lblL8 = new javax.swing.JLabel();
        lblL9 = new javax.swing.JLabel();
        lblL10 = new javax.swing.JLabel();
        lblL11 = new javax.swing.JLabel();
        lblL12 = new javax.swing.JLabel();
        btnGenerate = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JLabel();
        btnVowels = new javax.swing.JLabel();
        btnConsonents = new javax.swing.JLabel();
        lblRound = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        pnlTitle.setOpaque(false);
        pnlTitle.setPreferredSize(new java.awt.Dimension(806, 90));

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 806, Short.MAX_VALUE)
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        add(pnlTitle, java.awt.BorderLayout.PAGE_START);

        pnlContainer.setBackground(new java.awt.Color(102, 255, 255));
        pnlContainer.setFocusable(false);
        pnlContainer.setMaximumSize(new java.awt.Dimension(806, 37000));
        pnlContainer.setMinimumSize(new java.awt.Dimension(806, 510));
        pnlContainer.setOpaque(false);

        pnlPlayingArea.setBackground(new java.awt.Color(255, 51, 51));
        pnlPlayingArea.setFocusable(false);
        pnlPlayingArea.setMaximumSize(new java.awt.Dimension(570, 510));
        pnlPlayingArea.setMinimumSize(new java.awt.Dimension(570, 510));
        pnlPlayingArea.setOpaque(false);
        pnlPlayingArea.setPreferredSize(new java.awt.Dimension(570, 500));

        lblPlayerName.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lblPlayerName.setForeground(new java.awt.Color(255, 255, 255));
        lblPlayerName.setText("Player Name");
        lblPlayerName.setName("PlayerName"); // NOI18N

        lblPos.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lblPos.setForeground(new java.awt.Color(255, 255, 255));
        lblPos.setText("Position :");
        lblPos.setName("PlayerPosition"); // NOI18N

        lblScore.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lblScore.setForeground(new java.awt.Color(255, 255, 255));
        lblScore.setText("Score : ");
        lblScore.setToolTipText("");
        lblScore.setName("PlayerScore"); // NOI18N

        txtAnswer.setBackground(new java.awt.Color(0, 91, 127));
        txtAnswer.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        txtAnswer.setForeground(new java.awt.Color(255, 255, 255));
        txtAnswer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAnswer.setText("Answer");
        txtAnswer.setBorder(null);

        lblL2.setBackground(new java.awt.Color(0, 174, 239));
        lblL2.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        lblL2.setForeground(new java.awt.Color(255, 255, 255));
        lblL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblL2.setText("A");
        lblL2.setToolTipText("");
        lblL2.setMaximumSize(new java.awt.Dimension(40, 43));
        lblL2.setMinimumSize(new java.awt.Dimension(40, 43));
        lblL2.setName(""); // NOI18N
        lblL2.setOpaque(true);
        lblL2.setPreferredSize(new java.awt.Dimension(40, 43));

        lblL1.setBackground(new java.awt.Color(0, 174, 239));
        lblL1.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        lblL1.setForeground(new java.awt.Color(255, 255, 255));
        lblL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblL1.setText("A");
        lblL1.setToolTipText("");
        lblL1.setMaximumSize(new java.awt.Dimension(40, 43));
        lblL1.setMinimumSize(new java.awt.Dimension(40, 43));
        lblL1.setOpaque(true);
        lblL1.setPreferredSize(new java.awt.Dimension(40, 43));

        lblL4.setBackground(new java.awt.Color(0, 174, 239));
        lblL4.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        lblL4.setForeground(new java.awt.Color(255, 255, 255));
        lblL4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblL4.setText("A");
        lblL4.setToolTipText("");
        lblL4.setMaximumSize(new java.awt.Dimension(40, 43));
        lblL4.setMinimumSize(new java.awt.Dimension(40, 43));
        lblL4.setOpaque(true);
        lblL4.setPreferredSize(new java.awt.Dimension(40, 43));

        lblL3.setBackground(new java.awt.Color(0, 174, 239));
        lblL3.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        lblL3.setForeground(new java.awt.Color(255, 255, 255));
        lblL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblL3.setText("A");
        lblL3.setToolTipText("");
        lblL3.setMaximumSize(new java.awt.Dimension(40, 43));
        lblL3.setMinimumSize(new java.awt.Dimension(40, 43));
        lblL3.setOpaque(true);
        lblL3.setPreferredSize(new java.awt.Dimension(40, 43));

        lblL7.setBackground(new java.awt.Color(0, 174, 239));
        lblL7.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        lblL7.setForeground(new java.awt.Color(255, 255, 255));
        lblL7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblL7.setText("A");
        lblL7.setToolTipText("");
        lblL7.setMaximumSize(new java.awt.Dimension(40, 43));
        lblL7.setMinimumSize(new java.awt.Dimension(40, 43));
        lblL7.setOpaque(true);
        lblL7.setPreferredSize(new java.awt.Dimension(40, 43));

        lblL5.setBackground(new java.awt.Color(0, 174, 239));
        lblL5.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        lblL5.setForeground(new java.awt.Color(255, 255, 255));
        lblL5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblL5.setText("A");
        lblL5.setToolTipText("");
        lblL5.setMaximumSize(new java.awt.Dimension(40, 43));
        lblL5.setMinimumSize(new java.awt.Dimension(40, 43));
        lblL5.setOpaque(true);
        lblL5.setPreferredSize(new java.awt.Dimension(40, 43));

        lblL6.setBackground(new java.awt.Color(0, 174, 239));
        lblL6.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        lblL6.setForeground(new java.awt.Color(255, 255, 255));
        lblL6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblL6.setText("A");
        lblL6.setToolTipText("");
        lblL6.setMaximumSize(new java.awt.Dimension(40, 43));
        lblL6.setMinimumSize(new java.awt.Dimension(40, 43));
        lblL6.setOpaque(true);
        lblL6.setPreferredSize(new java.awt.Dimension(40, 43));

        lblL8.setBackground(new java.awt.Color(0, 174, 239));
        lblL8.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        lblL8.setForeground(new java.awt.Color(255, 255, 255));
        lblL8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblL8.setText("A");
        lblL8.setToolTipText("");
        lblL8.setMaximumSize(new java.awt.Dimension(40, 43));
        lblL8.setMinimumSize(new java.awt.Dimension(40, 43));
        lblL8.setOpaque(true);
        lblL8.setPreferredSize(new java.awt.Dimension(40, 43));

        lblL9.setBackground(new java.awt.Color(0, 174, 239));
        lblL9.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        lblL9.setForeground(new java.awt.Color(255, 255, 255));
        lblL9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblL9.setText("A");
        lblL9.setToolTipText("");
        lblL9.setMaximumSize(new java.awt.Dimension(40, 43));
        lblL9.setMinimumSize(new java.awt.Dimension(40, 43));
        lblL9.setOpaque(true);
        lblL9.setPreferredSize(new java.awt.Dimension(40, 43));

        lblL10.setBackground(new java.awt.Color(0, 174, 239));
        lblL10.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        lblL10.setForeground(new java.awt.Color(255, 255, 255));
        lblL10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblL10.setText("A");
        lblL10.setToolTipText("");
        lblL10.setMaximumSize(new java.awt.Dimension(40, 43));
        lblL10.setMinimumSize(new java.awt.Dimension(40, 43));
        lblL10.setOpaque(true);
        lblL10.setPreferredSize(new java.awt.Dimension(40, 43));

        lblL11.setBackground(new java.awt.Color(0, 174, 239));
        lblL11.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        lblL11.setForeground(new java.awt.Color(255, 255, 255));
        lblL11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblL11.setText("A");
        lblL11.setToolTipText("");
        lblL11.setMaximumSize(new java.awt.Dimension(40, 43));
        lblL11.setMinimumSize(new java.awt.Dimension(40, 43));
        lblL11.setOpaque(true);
        lblL11.setPreferredSize(new java.awt.Dimension(40, 43));

        lblL12.setBackground(new java.awt.Color(0, 174, 239));
        lblL12.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        lblL12.setForeground(new java.awt.Color(255, 255, 255));
        lblL12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblL12.setText("A");
        lblL12.setToolTipText("");
        lblL12.setMaximumSize(new java.awt.Dimension(40, 43));
        lblL12.setMinimumSize(new java.awt.Dimension(40, 43));
        lblL12.setOpaque(true);
        lblL12.setPreferredSize(new java.awt.Dimension(40, 43));

        btnGenerate.setBackground(new java.awt.Color(0, 153, 153));
        btnGenerate.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnGenerate.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGenerate.setText("Generate");
        btnGenerate.setName("Gen"); // NOI18N
        btnGenerate.setOpaque(true);
        btnGenerate.setPreferredSize(new java.awt.Dimension(140, 32));

        btnSubmit.setBackground(new java.awt.Color(0, 153, 153));
        btnSubmit.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSubmit.setText("Submit");
        btnSubmit.setName("Submit"); // NOI18N
        btnSubmit.setOpaque(true);
        btnSubmit.setPreferredSize(new java.awt.Dimension(140, 32));

        btnVowels.setBackground(new java.awt.Color(0, 153, 153));
        btnVowels.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnVowels.setForeground(new java.awt.Color(255, 255, 255));
        btnVowels.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVowels.setText("Vowels");
        btnVowels.setName("Vowels"); // NOI18N
        btnVowels.setOpaque(true);
        btnVowels.setPreferredSize(new java.awt.Dimension(140, 32));

        btnConsonents.setBackground(new java.awt.Color(0, 153, 153));
        btnConsonents.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnConsonents.setForeground(new java.awt.Color(255, 255, 255));
        btnConsonents.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnConsonents.setText("Consonents");
        btnConsonents.setName("Consonents"); // NOI18N
        btnConsonents.setOpaque(true);
        btnConsonents.setPreferredSize(new java.awt.Dimension(140, 32));

        lblRound.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lblRound.setForeground(new java.awt.Color(255, 255, 255));
        lblRound.setText("Round :");
        lblRound.setName("round"); // NOI18N

        javax.swing.GroupLayout pnlPlayingAreaLayout = new javax.swing.GroupLayout(pnlPlayingArea);
        pnlPlayingArea.setLayout(pnlPlayingAreaLayout);
        pnlPlayingAreaLayout.setHorizontalGroup(
            pnlPlayingAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlayingAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPlayingAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPlayingAreaLayout.createSequentialGroup()
                        .addComponent(lblPlayerName)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlPlayingAreaLayout.createSequentialGroup()
                        .addGroup(pnlPlayingAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPlayingAreaLayout.createSequentialGroup()
                                .addComponent(lblL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblL3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblPos))
                        .addGroup(pnlPlayingAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPlayingAreaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 322, Short.MAX_VALUE)
                                .addComponent(lblScore)
                                .addGap(30, 30, 30))
                            .addGroup(pnlPlayingAreaLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblL4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblL5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblL6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblL7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblL8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblL9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblL10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblL11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblL12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(pnlPlayingAreaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(txtAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlPlayingAreaLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(btnGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
            .addGroup(pnlPlayingAreaLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(btnVowels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConsonents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
            .addGroup(pnlPlayingAreaLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(lblRound)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPlayingAreaLayout.setVerticalGroup(
            pnlPlayingAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlayingAreaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblPlayerName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPlayingAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPos)
                    .addComponent(lblScore))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(lblRound)
                .addGap(39, 39, 39)
                .addGroup(pnlPlayingAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblL4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblL3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblL5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblL6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblL7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblL8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblL9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblL10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblL11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblL12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(pnlPlayingAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVowels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsonents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(txtAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(pnlPlayingAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );

        jPanel3.setBackground(new java.awt.Color(102, 204, 255));
        jPanel3.setFocusable(false);
        jPanel3.setMaximumSize(new java.awt.Dimension(230, 37000));
        jPanel3.setMinimumSize(new java.awt.Dimension(230, 510));
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(230, 510));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlContainerLayout = new javax.swing.GroupLayout(pnlContainer);
        pnlContainer.setLayout(pnlContainerLayout);
        pnlContainerLayout.setHorizontalGroup(
            pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContainerLayout.createSequentialGroup()
                .addComponent(pnlPlayingArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlContainerLayout.setVerticalGroup(
            pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPlayingArea, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlPlayingArea.getAccessibleContext().setAccessibleDescription("");

        add(pnlContainer, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnConsonents;
    private javax.swing.JLabel btnGenerate;
    private javax.swing.JLabel btnSubmit;
    private javax.swing.JLabel btnVowels;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblL1;
    private javax.swing.JLabel lblL10;
    private javax.swing.JLabel lblL11;
    private javax.swing.JLabel lblL12;
    private javax.swing.JLabel lblL2;
    private javax.swing.JLabel lblL3;
    private javax.swing.JLabel lblL4;
    private javax.swing.JLabel lblL5;
    private javax.swing.JLabel lblL6;
    private javax.swing.JLabel lblL7;
    private javax.swing.JLabel lblL8;
    private javax.swing.JLabel lblL9;
    private javax.swing.JLabel lblPlayerName;
    private javax.swing.JLabel lblPos;
    private javax.swing.JLabel lblRound;
    private javax.swing.JLabel lblScore;
    private javax.swing.JPanel pnlContainer;
    private javax.swing.JPanel pnlPlayingArea;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JTextField txtAnswer;
    // End of variables declaration//GEN-END:variables
}
