/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FLOG_GUI;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Dushan Galappaththi
 */
public class PanelWinners extends javax.swing.JPanel {

  /**
   * Creates new form PanelWinners
   */
  private Image bg;
  private GameScreen gameScreen;

  public PanelWinners(GameScreen gameScreen) {
    initComponents();
    bg = new ImageIcon(getClass().getResource("/images/bg_Leaderboard.png")).getImage();
    this.gameScreen = gameScreen;
  }

  @Override
  protected void paintComponent(Graphics g) {
    g.drawImage(bg, 0, 0, getWidth(), getHeight(), this);
  }

  public void setWinnerLabel(int rank) {
    switch (rank) {
      case 1:
        lblWinner.setVisible(true);
        lblLost.setVisible(false);
        lblFR.setVisible(false);
        lblSR.setVisible(false);
        break;

      case 2:
        lblWinner.setVisible(false);
        lblLost.setVisible(false);
        lblFR.setVisible(true);
        lblSR.setVisible(false);
        break;

      case 3:
        lblWinner.setVisible(false);
        lblLost.setVisible(false);
        lblFR.setVisible(false);
        lblSR.setVisible(true);
        break;

      default:
        lblWinner.setVisible(false);
        lblLost.setVisible(true);
        lblFR.setVisible(false);
        lblSR.setVisible(false);
        break;
    }
  }

  private void updatePlayersUI() {
    pnlPlayerInfoContainer.removeAll();
    revalidate();
    repaint();
  }

  public void drawPlayers() {
    boolean isFirstRound = true;
    pnlPlayerInfoContainer.setLayout(null);
    updatePlayersUI();
    JScrollPane jsp;
    JPanel pnlA = new JPanel();
    pnlA.setOpaque(false);
    pnlA.setLayout(new BoxLayout(pnlA, BoxLayout.PAGE_AXIS));
    pnlA.setBounds(0, 0, 700, 290);
    if (DataForUI.RoundNum > 1) {
      isFirstRound = false;
    }
    for (int i = 0; i < DataForUI.PdArray.length; i++) {
      pnlA.add(new ReadyPlayersUI(isFirstRound, i));
    }

    jsp = new JScrollPane(pnlA);
    jsp.setOpaque(false);
    jsp.setBorder(null);
    jsp.getViewport().setOpaque(false);
    pnlPlayerInfoContainer.add(jsp).setBounds(-82, -2, 800, 236);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWinner = new javax.swing.JLabel();
        lblLost = new javax.swing.JLabel();
        lblFR = new javax.swing.JLabel();
        lblSR = new javax.swing.JLabel();
        pnlPlayerInfoContainer = new javax.swing.JPanel();
        btnMainMenu = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(900, 619));
        setMinimumSize(new java.awt.Dimension(900, 619));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWinner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lbl_winner.png"))); // NOI18N
        add(lblWinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 140, -1, -1));

        lblLost.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lbl_Lost.png"))); // NOI18N
        add(lblLost, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 140, -1, -1));

        lblFR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lbl_firstrunnerup.png"))); // NOI18N
        add(lblFR, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 140, -1, -1));

        lblSR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lbl_secondrunnerup.png"))); // NOI18N
        add(lblSR, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 140, -1, -1));

        pnlPlayerInfoContainer.setOpaque(false);

        javax.swing.GroupLayout pnlPlayerInfoContainerLayout = new javax.swing.GroupLayout(pnlPlayerInfoContainer);
        pnlPlayerInfoContainer.setLayout(pnlPlayerInfoContainerLayout);
        pnlPlayerInfoContainerLayout.setHorizontalGroup(
            pnlPlayerInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
        );
        pnlPlayerInfoContainerLayout.setVerticalGroup(
            pnlPlayerInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        add(pnlPlayerInfoContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 240, 616, 290));

        btnMainMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_mainmenu_n.png"))); // NOI18N
        btnMainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMainMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMainMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMainMenuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMainMenuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMainMenuMouseReleased(evt);
            }
        });
        add(btnMainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnMainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMainMenuMouseClicked
        // TODO add your handling code here:
        gameScreen.changeScreen(DataForUI.STR_MAINMENU, DataForUI.STR_WINNER);
        btnMainMenu.setIcon(new ImageIcon(getClass().getResource("/images/btn_mainmenu_n.png")));
        
    }//GEN-LAST:event_btnMainMenuMouseClicked

    private void btnMainMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMainMenuMouseEntered
        // TODO add your handling code here:
        btnMainMenu.setIcon(new ImageIcon(getClass().getResource("/images/btn_mainmenu_n.png")));
    }//GEN-LAST:event_btnMainMenuMouseEntered

    private void btnMainMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMainMenuMouseExited
        // TODO add your handling code here:
        btnMainMenu.setIcon(new ImageIcon(getClass().getResource("/images/btn_mainmenu_n.png")));
    }//GEN-LAST:event_btnMainMenuMouseExited

    private void btnMainMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMainMenuMousePressed
         btnMainMenu.setIcon(new ImageIcon(getClass().getResource("/images/btn_mainmenu_n.png")));
    }//GEN-LAST:event_btnMainMenuMousePressed

    private void btnMainMenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMainMenuMouseReleased
        btnMainMenu.setIcon(new ImageIcon(getClass().getResource("/images/btn_mainmenu_n.png")));
    }//GEN-LAST:event_btnMainMenuMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnMainMenu;
    private javax.swing.JLabel lblFR;
    private javax.swing.JLabel lblLost;
    private javax.swing.JLabel lblSR;
    private javax.swing.JLabel lblWinner;
    private javax.swing.JPanel pnlPlayerInfoContainer;
    // End of variables declaration//GEN-END:variables
}
