/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FLOG_GUI;

import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Dushan Galappaththi
 */
public class PanelRoundReadyUp extends javax.swing.JPanel {

    /**
     * Creates new form PanelRoundReadyUp
     */
    private Image bg;
    DataForUI DataForUI;
    public PanelRoundReadyUp() {
        initComponents();
        bg = new ImageIcon(getClass().getResource("/images/bg_roundReadyUp.png")).getImage();
        DataForUI= new DataForUI();
        lblTitlePlayersInfo.setVisible(false);
    }
    
    public void setTimer(String tmr)
     {
         this.lblReadyUpTimer.setFont(DataForUI.LCD.deriveFont(Font.PLAIN, 40));       
         this.lblReadyUpTimer.setText(tmr);
     
     }
    
    public void setRound(String round)
    {
        this.lblRound.setText(round);
    }
    private void updatePlayersUI()
    {
        pnlPlayerInfoContainer.removeAll();
        revalidate();
        repaint();
    }
    
    /**
     * Dynamically display round score board/ready up player list
     */
    public void drawPlayers()
    {
        boolean isFirstRound = true;
        pnlPlayerInfoContainer.setLayout(null);
        updatePlayersUI();
        JScrollPane jsp;
        JPanel pnlA = new JPanel();
        pnlA.setOpaque(false);
        pnlA.setLayout(new BoxLayout(pnlA, BoxLayout.PAGE_AXIS));
        pnlA.setBounds(0,0, 700, 290);
        if(DataForUI.RoundNum>1)
        {
            isFirstRound = false;
        }
        for(int i=0;i<DataForUI.PdArray.length;i++)
       {
          pnlA.add(new ReadyPlayersUI(isFirstRound,i));
       }
        
        jsp = new JScrollPane(pnlA);
        jsp.setOpaque(false);
        jsp.setBorder(null);
        jsp.getViewport().setOpaque(false);
        pnlPlayerInfoContainer.add(jsp).setBounds(-82,0, 800, 290);
    }
    
    public void setTitlePlayers(boolean isPlayers)
    {
        if(isPlayers)
        {
            lblTitlePlayers.setVisible(true);
            lblTitlePlayersInfo.setVisible(false);
        }
        else
        {
            lblTitlePlayers.setVisible(false);
            lblTitlePlayersInfo.setVisible(true);
        }
    }
    @Override
    protected void paintComponent(Graphics g) {
         g.drawImage(bg, 0, 0, getWidth(), getHeight(), this);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblReadyUpTimer = new javax.swing.JLabel();
        lblRound = new javax.swing.JLabel();
        pnlPlayerInfoContainer = new javax.swing.JPanel();
        lblTitlePlayers = new javax.swing.JLabel();
        lblTitlePlayersInfo = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(900, 619));
        setMinimumSize(new java.awt.Dimension(900, 619));
        setPreferredSize(new java.awt.Dimension(900, 619));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblReadyUpTimer.setFont(new java.awt.Font("Times New Roman", 0, 40)); // NOI18N
        lblReadyUpTimer.setForeground(new java.awt.Color(255, 255, 255));
        lblReadyUpTimer.setText("  ");
        add(lblReadyUpTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 140, -1, -1));

        lblRound.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        lblRound.setForeground(new java.awt.Color(255, 255, 255));
        lblRound.setText("1");
        add(lblRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 142, -1, -1));

        pnlPlayerInfoContainer.setBackground(new java.awt.Color(204, 255, 255));
        pnlPlayerInfoContainer.setOpaque(false);
        pnlPlayerInfoContainer.setLayout(null);
        add(pnlPlayerInfoContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 240, 616, 290));

        lblTitlePlayers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lbl_players.png"))); // NOI18N
        lblTitlePlayers.setToolTipText("");
        add(lblTitlePlayers, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 198, -1, -1));

        lblTitlePlayersInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lbl_players_full.png"))); // NOI18N
        add(lblTitlePlayersInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 198, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblReadyUpTimer;
    private javax.swing.JLabel lblRound;
    private javax.swing.JLabel lblTitlePlayers;
    private javax.swing.JLabel lblTitlePlayersInfo;
    private javax.swing.JPanel pnlPlayerInfoContainer;
    // End of variables declaration//GEN-END:variables
}
