/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FLOG_GUI;

import java.awt.Component;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Dushan Galappaththi
 */
public class PanelRegister extends javax.swing.JPanel {

  private Image bg;

  public PanelRegister() {
    initComponents();
    bg = new ImageIcon(getClass().getResource("/images/bg_register.png")).getImage();
  }

  public Component getCompTop(int x) {
    Component[] cmpList = this.getComponents();
    /*
    for(int i =0;i<cmpList.length;i++)
    {
          System.out.println(i + " "+cmpList[i].getY()+" "+ cmpList[i].getName() );
    }*/
    return this.pnlTopBorder.getComponent(x);
  }

  public Component getCompCon(int x) {
    Component[] cmpList = this.getComponents();

    /*for(int i =0;i<cmpList.length;i++)
    {
          System.out.println(i + " "+cmpList[i].getY()+" "+ cmpList[i].getName() );
    }*/
    return this.getComponent(x);
  }

  public void setIcon_Register(ImageIcon imgIcon) {
    this.btnSignUp.setIcon(imgIcon);
  }

  public void setIcon_Cancel(ImageIcon imgIcon) {
    this.btnCancel.setIcon(imgIcon);
  }

  @Override
  protected void paintComponent(Graphics g) {
    g.drawImage(bg, 0, 0, getWidth(), getHeight(), this);
  }
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    pnlTopBorder = new javax.swing.JPanel();
    btnExit = new javax.swing.JLabel();
    txtUsername = new javax.swing.JTextField();
    txtPass = new javax.swing.JPasswordField();
    txtConPass = new javax.swing.JPasswordField();
    btnSignUp = new javax.swing.JLabel();
    btnCancel = new javax.swing.JLabel();
    txtEmail = new javax.swing.JTextField();

    setMaximumSize(new java.awt.Dimension(900, 619));
    setMinimumSize(new java.awt.Dimension(900, 619));
    setPreferredSize(new java.awt.Dimension(900, 619));
    setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    pnlTopBorder.setName("topBorder-reg"); // NOI18N
    pnlTopBorder.setOpaque(false);
    pnlTopBorder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    btnExit.setText("exit");
    btnExit.setName("exit-reg"); // NOI18N
    pnlTopBorder.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(856, 11, -1, -1));

    add(pnlTopBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 38));

    txtUsername.setText("username");
    txtUsername.setBorder(null);
    txtUsername.setName("uname-reg"); // NOI18N
    add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 224, 140, 25));

    txtPass.setBorder(null);
    txtPass.setName("pass -reg"); // NOI18N
    add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 299, 140, 25));

    txtConPass.setBorder(null);
    txtConPass.setName("confirmPass-reg"); // NOI18N
    add(txtConPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 380, 140, 25));

    btnSignUp.setIcon(
        new javax.swing.ImageIcon(getClass().getResource("/images/btn_register_n.png"))); // NOI18N
    btnSignUp.setName("signup-reg"); // NOI18N
    add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 500, -1, -1));

    btnCancel.setIcon(
        new javax.swing.ImageIcon(getClass().getResource("/images/btn_cancel_n.png"))); // NOI18N
    btnCancel.setName("cancel-reg"); // NOI18N
    add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 500, -1, -1));

    txtEmail.setText("email");
    txtEmail.setBorder(null);
    add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 456, 207, 28));
  } // </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel btnCancel;
  private javax.swing.JLabel btnExit;
  private javax.swing.JLabel btnSignUp;
  private javax.swing.JPanel pnlTopBorder;
  private javax.swing.JPasswordField txtConPass;
  private javax.swing.JTextField txtEmail;
  private javax.swing.JPasswordField txtPass;
  private javax.swing.JTextField txtUsername;
  // End of variables declaration//GEN-END:variables
}
