/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FLOG_GUI;
import FLOG_LOGIC.*;
import FLOG_LOGIC.Multiplayer;

import FLOG_LOGIC.Thrower;
import FLOG_LOGIC.ThrowListener;

import java.awt.event.MouseEvent;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JPanel;


/**
 *
 * @author Pasindu
 */
public class SelectMultiPlayer extends JPanel {
    /** Name of the channel the user is hosting or joined. */
    public String channelName = null;
    /** Name of the player. */
    private String playerName = null;
    int posX=0,posY=0;
    private boolean IS_USER_JOINED = false;
    // Consumer producer client
    Catcher clientCatcher = new Catcher();
    Thrower clientThrower = new Thrower();
    Multiplayer multiplayer = new Multiplayer();
    
    /**
     * Creates new form SelectMultiPlayer
     */
    public SelectMultiPlayer() {
        initComponents();
        clientThrower.addThrowListener(clientCatcher);
    }
    
    private Server server = null;
    
    /**
     * Decode the message received by the client
     */
    public synchronized void decodeClientMessage(String message) {
        setClientStatus("Message in client - " + message);
        String[] segments = message.split(" ");
        if (segments.length < 2) {
            return;
        }
        String code = segments[0];
        String content = segments[1];
        switch (code) {
            case "200":
                // User joined the correctly.
                break;
            case "201":
                this.playerName = txtPlayerName.getText().trim();
                // TODO add player names.
                MultiPlayerTestGUI gui = new MultiPlayerTestGUI(this.channelName, this.playerName, null);
                gui.setVisible(true);
                break;
        }
    }
    
    /**
     * Listens to messages thrown by checkQueueThread.
     */
    public class Catcher implements ThrowListener {
        @Override
        public void Catch(String message) {
            System.out.println("Caught " + message);
            decodeClientMessage(message);
        }
    }
    
    /**
     * Start the server queues for the give {@code channelName}
     */
    private void startServerButtonMouseClicked(MouseEvent evt) {
        channelName = txtChannelName.getText();
        multiplayer.createServer(channelName);
        setServerStatus("Starting Server");
        // Server listen's to it's queue.
        server = new Server(channelName);
        server.start();
        setServerStatus("Sever started");
        startServerButton.setEnabled(false);
    }

    /**
     * Join the given server {@code channelName}
     */
    private void joinServerButtonMouseClicked(MouseEvent evt) {
        setClientStatus("Joining server");
        channelName = txtChannelName.getText();
        playerName = txtPlayerName.getText();
        multiplayer.joinNewPlayer(playerName, channelName);

        // Listen to the client's queue.
        String clientQueueName = multiplayer.getClientQueue(channelName, playerName);
        Thread backgroundClientQueueCheck = new CheckQueueThread(clientQueueName, clientThrower);
        backgroundClientQueueCheck.start();
        joinServerButton.setEnabled(false);
    }

    /**
     * Set the status from the queue reading.
     */
    public synchronized void setServerStatus(String status) {
        System.out.println("Set status " + status);
        String text = jTextPane2.getText();
        jTextPane2.setText(text += "\n" + status);
    }
    
    
    /** Set of the server status. */
    public synchronized void setClientStatus(String status){
        System.out.println("Set status client - " + status);
        String text = txtClientMessages.getText();
        txtClientMessages.setText(text += "\n" + status);
    }
    
      /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtChannelName = new javax.swing.JTextPane();
        startServerButton = new javax.swing.JButton();
        joinServerButton = new javax.swing.JButton();
        btnStartGame = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtPlayerName = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtClientMessages = new javax.swing.JTextArea();

        txtChannelName.setText("ChannelName");
        jScrollPane1.setViewportView(txtChannelName);

        startServerButton.setText("Start Server");
        startServerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startServerButtonMouseClicked(evt);
            }
        });

        joinServerButton.setText("Join Multiplayer");
        joinServerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                joinServerButtonMouseClicked(evt);
            }
        });

        btnStartGame.setText("Start Game");
        btnStartGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStartGameMouseClicked(evt);
            }
        });

        jTextPane2.setText("Server messages - ");
        jTextPane2.setToolTipText("");
        jScrollPane2.setViewportView(jTextPane2);

        jScrollPane3.setViewportView(txtPlayerName);

        txtClientMessages.setColumns(20);
        txtClientMessages.setRows(5);
        txtClientMessages.setText("Client messages -");
        jScrollPane4.setViewportView(txtClientMessages);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)
                        .addComponent(startServerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(joinServerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                        .addComponent(btnStartGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(startServerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(joinServerButton)
                .addGap(18, 18, 18)
                .addComponent(btnStartGame)
                .addContainerGap(154, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartGameMouseClicked
        channelName = txtChannelName.getText();
        playerName = txtPlayerName.getText();
        server.startGame();
    }//GEN-LAST:event_btnStartGameMouseClicked

    // Listen
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStartGame;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JButton joinServerButton;
    private javax.swing.JButton startServerButton;
    private javax.swing.JTextPane txtChannelName;
    private javax.swing.JTextArea txtClientMessages;
    private javax.swing.JTextPane txtPlayerName;
    // End of variables declaration//GEN-END:variables
}





